### ISSUE TITLE
Error: Cannot find module '../entities/photosize'

### ISSUE THREAD

**Issue by Smolevich** [Snowfire01/telegram-stat-bot#17]
Dockefile: 
```dockerfile
FROM node

WORKDIR /usr/src/app

COPY package.json ./

RUN npm i

COPY . .

RUN npm build

ENTRYPOINT ["npm", "start"]
```

docker-compose.yml

```yaml
version: '3.7'

services:
  bot:
    image: stats-bot:1.0
    build:
      context: .
    env_file:
      - .env
  mongo:
    image: mongo
    volumes:
    - ./data:/data/db:rw
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: stats
      MONGO_INITDB_ROOT_PASSWORD: stats
      MONGO_INITDB_DATABASE: stats
    command: --auth
```

Logs: 
```

> telegram-stat-bot@0.0.1 start
> node scripts/setupConfig.js && "node_modules/.bin/babel-node" src/index.js

Configuration file found. Starting server.
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module '../entities/photosize'
Require stack:
- /usr/src/app/src/models/messageTypes/audio.js
- /usr/src/app/src/models/entities/message.js
- /usr/src/app/src/models/schemas/message.schema.js
- /usr/src/app/src/databaseAccess/getAllTexts.db.js
- /usr/src/app/src/controllers/message.controller.js
- /usr/src/app/src/routes/messages/getMessageTotal.route.js
- /usr/src/app/src/routes/index.route.js
- /usr/src/app/src/setupFunctions.js
- /usr/src/app/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/src/app/src/models/messageTypes/audio.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at loader (/usr/src/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/usr/src/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/src/app/src/models/entities/message.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at loader (/usr/src/app/node_modules/babel-register/lib/node.js:144:5)
     at Object.require.extensions.<computed> [as .js] (/usr/src/app/node_modules/babel-register/lib/node.js:154:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/src/models/messageTypes/audio.js',
    '/usr/src/app/src/models/entities/message.js',
    '/usr/src/app/src/models/schemas/message.schema.js',
    '/usr/src/app/src/databaseAccess/getAllTexts.db.js',
    '/usr/src/app/src/controllers/message.controller.js',
    '/usr/src/app/src/routes/messages/getMessageTotal.route.js',
    '/usr/src/app/src/routes/index.route.js',
    '/usr/src/app/src/setupFunctions.js',
    '/usr/src/app/src/index.js'
  ]
}
```
